name: Django Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: "djt.settings.localhost"
        SECRET_KEY: 'jdklasjkldklsa'

        # Database
        DATABASE_URL: 'postgresql://fin:fin@localhost:15432/fin'
        DB_SSL_REQUIRE: False

        # Domain
        PROJECT_MAIN_DOMAIN: 'localhost'
        ALLOWED_HOSTS: 'localhost, 127.0.0.1'
        CSRF_TRUSTED_ORIGINS: 'http://localhost:8000'
        CORS_ALLOWED_ORIGINS: 'http://localhost:8000'
