name: lint

on:
  push:
    branches: ['*'] # všechny větve spouští lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install Dependencies
        run: |
          pip install flake8
      - name: Lint
        run: |
          flake8 djt/