name: New Branche CI/CD


on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint code
        run: |
          echo "Linting code"
  test:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test code
        run: |
          echo "Testing code"