name: Production CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint code
        run: |
          echo "Linting code"
  test:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test code
        run: |
          echo "Testing code"
  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build code
        run: |
          echo "Building code"

  deploy_to_production:
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Master
        run: |
          echo "Deployment script for master"

    #  deploy:
    #    if: github.ref == 'refs/heads/master'
    #    runs-on: [ ubuntu-latest ]
    #    steps:
    #      - uses: actions/checkout@v1
    #      - name: Push to server
    #        uses: appleboy/ssh-action@master
    #        with:
    #          host: YOUR_SERVER_IP
    #          username: USER_NAME
    #          password: PASSWORD
    #          script: |
    #            cd YOUR_PROJECT
    #            git pull
    #            docker-compose down
    #            docker-compose up -d