name: Production CI/CD

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [closed]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint code
        run: |
          echo "Linting code"
  test:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test code
        run: |
          echo "Testing code"
  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build code
        run: |
          echo "Building code"

  deploy_to_production:
    needs: lint
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Master
        run: |
          echo "Deployment script for master"